version: "3"

services:
  postgres-docker:
    image: postgres
    container_name: DockerPostgres
    volumes:
      - ${POSTGRES_HOST_DIR}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mysql-docker:
    image: mysql
    container_name: DockerMySQL
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_HOST_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}